### ISSUE TITLE
KeyError: "['hospitaladmityear'] not in index"

### ISSUE THREAD

**Issue by xlbryantx** [mostafaalishahi/eICU_Benchmark#3]
When I Execute the command python data_extraction_root.py， I got:
KeyError: "['hospitaladmityear'] not in index"
Then I found in the current patient.csv file, the column "hospitalAdmitYear" seems to be missing. "hospitaladmittime24" is there though.

**Comment by mostafaalishahi** [comment]
Thanks for your interest in this work, Please check out the latest version of the code in [https://github.com/mostafaalishahi/eICU_Benchmark_updated] and there should not be any issues. however, we do not use any of these columns in the analysis.
